language: python
python: 2.7
env:
  - TOXENV=py3.6
  - TOXENV=py3.4
  - TOXENV=py2.7
  - TOXENV=py2.6
install:
  - pip install tox coveralls
script:
  coverage run --source=pathfinding setup.py test
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
